version: 2.1
defaults: &default-docker
  docker:
    - image: circleci/node:13.8.0
jobs:
  build:
    <<: *default-docker
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    <<: *default-docker
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  analyze:
    <<: *default-docker
    steps:
      - checkout
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test